/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
      login: [];
      'login.store': [];
      logout: [];
      'password.request': [];
      'password.reset': [
          {
              name: 'token';
              required: true;
          },
      ];
      'password.email': [];
      'password.update': [];
      register: [];
      'register.store': [];
      'verification.notice': [];
      'verification.verify': [
          {
              name: 'id';
              required: true;
          },
          {
              name: 'hash';
              required: true;
          },
      ];
      'verification.send': [];
      'password.confirm': [];
      'password.confirmation': [];
      'password.confirm.store': [];
      'two-factor.login': [];
      'two-factor.login.store': [];
      'two-factor.enable': [];
      'two-factor.confirm': [];
      'two-factor.disable': [];
      'two-factor.qr-code': [];
      'two-factor.secret-key': [];
      'two-factor.recovery-codes': [];
      'two-factor.regenerate-recovery-codes': [];
      home: [];
      'posts.index': [];
      'posts.show': [
          {
              name: 'post';
              required: true;
              binding: 'id';
          },
      ];
      'posts.comments.store': [
          {
              name: 'post';
              required: true;
              binding: 'id';
          },
      ];
      'posts.comments.destroy': [
          {
              name: 'post';
              required: true;
              binding: 'id';
          },
          {
              name: 'comment';
              required: true;
              binding: 'id';
          },
      ];
      'profile.edit': [];
      'profile.update': [];
      'profile.destroy': [];
      'security.edit': [];
      'user-password.update': [];
      'appearance.edit': [];
      'storage.local': [
          {
              name: 'path';
              required: true;
          },
      ];
      'storage.local.upload': [
          {
              name: 'path';
              required: true;
          },
      ];
  }
}
export {};
